language: python

python:
  - 3.6
  - 3.7
  - 3.8

sudo: required

services:
  - rabbitmq

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install pytest-cov
  - pip install codecov

install:
  - pip install .

script:
  - pytest --cov=pokeman

after_success:
  - codecov

matrix:
  include:
    - name: "Python 3.5.4 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.5.4
        - python --version
        - python -m pip install --upgrade pip
        - pip3 install --upgrade pytest
        - pip3 install codecov
      env: PATH=/c/Python35:/c/Python35/Scripts:$PATH